language: cpp

env:
  global:
   - RUN_TESTS = true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      addons:
      apt:
        packages:
        - cmake-data
        - cmake
        - gcc-7
        - g++-7
        sources:
        - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake # install cmake
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib

install:
  #- |
  #  if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
  - sudo apt-get purge cmake
  - CMAKE_INSTALLER=install-cmake.sh
  - curl -sSL https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh -o ${CMAKE_INSTALLER}
  - chmod +x ${CMAKE_INSTALLER}
  - sudo ./${CMAKE_INSTALLER} --prefix=/usr/local --skip-license
  #  fi
  
script:
     - cd /home/travis/build/AAndrija/testing
     - sudo mkdir -p build
     - cd build
     - sudo CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake ../src -Dalignment_build_tests=ON -Dbuild_mapper=OFF
     - sudo cmake --build .
     - ./pink_alignment_test