dist: trusty
sudo: required
language:
  -cpp
compiler:
  -gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      #- cmake-data
      #- cmake

before_install:
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake
  
script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - cd /usr/src/gtest
  - ls /usr/local/cmake-3.9.2 -a
  - ls /usr/local/bin
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd /home/travis/build/AAndrija/testing
  - sudo mkdir build
  - cd build
  - ls ../src
  - sudo cmake ../src -Dalignment_build_tests=ON -Dbuild_mapper=OFF
  - sudo cmake --build .
  - ./pink_alignment_test