#dist: trusty
#sudo: required
language:
  - cpp
#compiler:
#  - gcc
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - clang-3.7
#      - gcc-6
#      - g++-6
      #- cmake-data
      #- cmake

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
          - g++-6
          
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
        packages:
          - clang-3.7
          - clang++-3.7



before_install:
  - sudo apt-get install libgtest-dev
  - sudo apt-get remove cmake cmake-data
  - sudo -E add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo -E apt-get update
  - sudo apt-get install cmake

install:
  - cd /usr/src/gtest
  - sudo cmake -DBUILD_SHARED_LIBS=ON
  - sudo make
  - sudo cp *.so /usr/lib
  
script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - ls /usr/local/cmake-3.9.2 -a
  - ls /usr/local/bin
  - | 
    if [[ ${TRAVIS_COMPILER} == "clang"]]; then
      export CC=/usr/bin/clang
      export CXX=/usr/bin/clang++
    fi
  - cd /home/travis/build/AAndrija/testing
  - mkdir build
  - cd build
  - ls ../src
  - sudo cmake ../src -Dalignment_build_tests=ON -Dbuild_mapper=OFF
  - sudo cmake --build .
  - ./pink_alignment_test