dist: trusty
sudo: required
language:
  -cpp
compiler:
  -gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake-data
      - cmake

before_install:
  - sudo apt-get install libgtest-dev
  
  
script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd /home/travis/build/AAndrija/testing
  - sudo mkdir build
  - cd build
  - CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - sudo cmake ../src -Dalignment_build_tests=ON -Dbuild_mapper=OFF
  - sudo cmake --build .
  - ./pink_alignment_test