language: cpp

env:
  global:
   - RUN_TESTS = true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      become: yes
      compiler: gcc
      addons:
      apt:
        packages:
        - gcc-7
        - g++-7
        sources:
        - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
  - chmod +x cmake-3.7.2-Linux-x86_64.sh
  - ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
install:
  
script:
     - cd /home/travis/build/AAndrija/testing
     - sudo mkdir -p build
     - cd build
     - sudo cmake ../src -Dalignment_build_tests=ON -Dbuild_mapper=OFF
     - sudo cmake --build .
     - ./pink_alignment_test