language: cpp

env:
  global:
   - RUN_TESTS = true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      addons:
      apt:
        packages:
        - cmake-data
        - cmake
        - gcc-7
        - g++-7
        sources:
        - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake # install cmake
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib

install:
  #- |
  #  if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
  - CMAKE_URL="https://cmake.org/files/LatestRelease/cmake-3.18.0-Linux-x86_64.tar.gz"
  - sudo mkdir -p ${DEPS_DIR}/cmake
  - sudo travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
  - sudo export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  #  fi
  
script:
     - cd /home/travis/build/AAndrija/testing
     - sudo mkdir -p build
     - cd build
     - sudo CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake ../src -Dalignment_build_tests=ON -Dbuild_mapper=OFF
     - sudo cmake --build .
     - ./pink_alignment_test