language: cpp

env:
  global:
   - RUN_TESTS = true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
      apt:
        packages:
        - cmake-data
        - cmake
        - gcc-4.8
        - g++-4.8
        sources:
        - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - sudo apt-get install libgtest-dev
  #- sudo apt-get install cmake=3.9.0 # install cmake
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  
script:
     - cd /home/travis/build/AAndrija/testing
     - sudo mkdir -p build
     - cd build
     - sudo cmake ../src -Dalignment_build_tests=ON -Dbuild_mapper=OFF
     - sudo cmake --build .
     - ./pink_alignment_test
	  
	